/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 0cc833c6680cfee617adffbc11ad98c3)
interface __BaseEnv_Env {
	ANALYTICS_KV: KVNamespace;
	STATS_DB: D1Database;
	ANTHROPIC_API_KEY: string;
	ANTHROPIC_MODEL: string;
	KONSEPTSPEILET_MOCK: string;
	STATS_TOKEN: string;
	FEATURE_TOGGLE_TOKEN: string;
	BETA_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANTHROPIC_API_KEY" | "ANTHROPIC_MODEL" | "KONSEPTSPEILET_MOCK" | "STATS_TOKEN" | "FEATURE_TOGGLE_TOKEN" | "BETA_TOKEN">> {}
}
