/**
 * Types for Antakelseskart - Assumption mapping tool
 * Makes implicit assumptions in product/strategy decisions explicit
 */

/**
 * Assumption categories
 */
export type AssumptionCategory =
  | 'målgruppe_behov'      // Target group & need
  | 'løsning_produkt'      // Solution & product
  | 'marked_konkurranse'   // Market & competition
  | 'forretning_skalering'; // Business model & scaling

/**
 * User-assigned certainty level
 */
export type CertaintyLevel = 'lav' | 'middels' | 'høy';

/**
 * User-assigned consequence if assumption is wrong
 */
export type ConsequenceLevel = 'lav' | 'middels' | 'høy';

/**
 * User-assigned status for the assumption
 */
export type AssumptionStatus = 'å_validere' | 'validert' | 'irrelevant';

/**
 * A single assumption generated by AI
 */
export interface Assumption {
  id: string;
  text: string;
  category: AssumptionCategory;
  // User-assigned values (optional, set after generation)
  certainty?: CertaintyLevel;
  consequence?: ConsequenceLevel;
  status?: AssumptionStatus;
}

/**
 * Grouped assumptions by category
 */
export interface GroupedAssumptions {
  målgruppe_behov: Assumption[];
  løsning_produkt: Assumption[];
  marked_konkurranse: Assumption[];
  forretning_skalering: Assumption[];
}

/**
 * The raw JSON response from the AI
 */
export interface AntakelseskartJsonResponse {
  beslutning_oppsummert: string;
  antakelser: GroupedAssumptions;
  antall_totalt: number;
}

/**
 * The parsed result with additional metadata
 */
export interface ParsedAntakelseskartResult {
  beslutningOppsummert: string;
  antakelser: GroupedAssumptions;
  antallTotalt: number;
  isComplete: boolean;
  parseError: string | null;
}

/**
 * Category labels in Norwegian for display
 */
export const CATEGORY_LABELS: Record<AssumptionCategory, { name: string; description: string }> = {
  målgruppe_behov: {
    name: 'Målgruppe og behov',
    description: 'Hvem er brukeren og hva trenger de?',
  },
  løsning_produkt: {
    name: 'Løsning og produkt',
    description: 'Hva bygger vi og hvordan fungerer det?',
  },
  marked_konkurranse: {
    name: 'Marked og konkurranse',
    description: 'Hvem konkurrerer vi med og hvordan?',
  },
  forretning_skalering: {
    name: 'Forretning og skalering',
    description: 'Hvordan tjener vi penger og vokser?',
  },
};

/**
 * Certainty labels in Norwegian
 */
export const CERTAINTY_LABELS: Record<CertaintyLevel, string> = {
  lav: 'Lav',
  middels: 'Middels',
  høy: 'Høy',
};

/**
 * Consequence labels in Norwegian
 */
export const CONSEQUENCE_LABELS: Record<ConsequenceLevel, string> = {
  lav: 'Lav',
  middels: 'Middels',
  høy: 'Høy',
};

/**
 * Status labels in Norwegian
 */
export const ASSUMPTION_STATUS_LABELS: Record<AssumptionStatus, string> = {
  å_validere: 'Å validere',
  validert: 'Validert',
  irrelevant: 'Irrelevant',
};

/**
 * Check if an assumption is critical (low certainty + high consequence)
 */
export function isCriticalAssumption(assumption: Assumption): boolean {
  return assumption.certainty === 'lav' && assumption.consequence === 'høy';
}

/**
 * Get all critical assumptions from grouped assumptions
 */
export function getCriticalAssumptions(grouped: GroupedAssumptions): Assumption[] {
  const all = [
    ...grouped.målgruppe_behov,
    ...grouped.løsning_produkt,
    ...grouped.marked_konkurranse,
    ...grouped.forretning_skalering,
  ];
  return all.filter(isCriticalAssumption);
}

/**
 * Generate a text summary of critical assumptions for export
 */
export function generateSummary(
  beslutning: string,
  grouped: GroupedAssumptions
): string {
  const critical = getCriticalAssumptions(grouped);

  let summary = `Beslutning: ${beslutning}\n\n`;
  summary += `Kritiske antakelser (${critical.length}):\n`;

  if (critical.length === 0) {
    summary += '- Ingen kritiske antakelser identifisert\n';
  } else {
    critical.forEach((a, i) => {
      summary += `${i + 1}. ${a.text}\n`;
    });
  }

  return summary;
}
